#!/bin/bash
TWITTER_CONSUMER_KEY="$TWITTER_CONSUMER_KEY" \
    TWITTER_CONSUMER_SECRET="$TWITTER_CONSUMER_SECRET" \
    TWITTER_ACCESS_TOKEN="$TWITTER_ACCESS_TOKEN" \
    TWITTER_ACCESS_TOKEN_SECRET="$TWITTER_ACCESS_SECRET" \
    WIKI_PASSWORD="$WIKI_PASSWORD" \
    /usr/local/bin/python3 /srv/tweetbot/tweet.py
