name: Post

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 16,20,0,4,8,12 * * *"
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Post
        if: github.repository_owner == 'femiwiki' && github.ref == 'refs/heads/main'
        run: uv run tweetbot
        env:
          MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
          FEMIWIKI_OAUTH1_CONSUMER_TOKEN: ${{ secrets.FEMIWIKI_OAUTH1_CONSUMER_TOKEN }}
          FEMIWIKI_OAUTH1_CONSUMER_SECRET: ${{ secrets.FEMIWIKI_OAUTH1_CONSUMER_SECRET }}
          FEMIWIKI_OAUTH1_ACCESS_TOKEN: ${{ secrets.FEMIWIKI_OAUTH1_ACCESS_TOKEN }}
          FEMIWIKI_OAUTH1_ACCESS_SECRET: ${{ secrets.FEMIWIKI_OAUTH1_ACCESS_SECRET }}
